In [1]:
# Array - Collection of similar type of data
import numpy as np

In [2]:
np.array([4,5,7,6,3,4,7,8,8])

array([4, 5, 7, 6, 3, 4, 7, 8, 8])

In [3]:
np.array([1,3,4,5,7,45.6,34.5])

array([ 1. ,  3. ,  4. ,  5. ,  7. , 45.6, 34.5])

In [4]:
np.array([1,3,4,5,7,45.6,34.5, True, 45])

array([ 1. ,  3. ,  4. ,  5. ,  7. , 45.6, 34.5,  1. , 45. ])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
# will always return a random number between 0 to 1
np.random.random()

0.5055509200769908

In [10]:
np.random.random(5)

array([0.46967663, 0.67317042, 0.83837111, 0.39498807, 0.44327809])

In [12]:
np.random.random([4,5])

array([[0.63352211, 0.53120837, 0.82508514, 0.71506359, 0.1213978 ],
       [0.81951405, 0.38573001, 0.4922672 , 0.77613099, 0.61102063],
       [0.60567936, 0.85639655, 0.35172511, 0.97306681, 0.97097491],
       [0.81357019, 0.60370736, 0.80874778, 0.04318722, 0.81279184]])

In [13]:
np.random.randint(1,100)

12

In [14]:
np.random.randint(1,100,10)

array([33, 79, 61, 24, 51, 67, 61, 76, 65, 92])

In [15]:
np.random.randint(1,100,(4,7))

array([[92, 53, 80, 31, 56,  6,  1],
       [16, 18, 16, 55, 83, 46, 51],
       [50, 23, 90, 47, 14,  8, 18],
       [35,  8, 84, 45, 68, 36, 66]])

In [16]:
x = np.random.randint(1,100,10)

In [17]:
x

array([30, 61, 41, 17, 58,  1, 53, 89, 82, 64])

In [18]:
x[0]

30

In [19]:
x[-1]

64

In [20]:
x[0:6]

array([30, 61, 41, 17, 58,  1])

In [21]:
x = np.random.randint(1,100,(6,7))

In [22]:
x

array([[ 8, 56, 53, 50, 11, 71, 40],
       [56, 88, 71, 64, 15, 31, 75],
       [33, 67, 20, 55, 27, 35, 31],
       [30, 77,  3,  2, 17,  3, 17],
       [ 2, 38, 23, 48, 43, 99, 63],
       [30, 61, 74, 24, 58, 63,  4]])

In [23]:
x.shape

(6, 7)

In [24]:
x[0]

array([ 8, 56, 53, 50, 11, 71, 40])

In [25]:
x[0][0]

8

In [26]:
x[0][3]

50

In [27]:
x[:, 0]

array([ 8, 56, 33, 30,  2, 30])

In [28]:
x[:, 0:3]

array([[ 8, 56, 53],
       [56, 88, 71],
       [33, 67, 20],
       [30, 77,  3],
       [ 2, 38, 23],
       [30, 61, 74]])

In [29]:
x[:, 3:6]

array([[50, 11, 71],
       [64, 15, 31],
       [55, 27, 35],
       [ 2, 17,  3],
       [48, 43, 99],
       [24, 58, 63]])

In [30]:
x[0:3,0:3]

array([[ 8, 56, 53],
       [56, 88, 71],
       [33, 67, 20]])

In [31]:
x[:, [0,3,5]]

array([[ 8, 50, 71],
       [56, 64, 31],
       [33, 55, 35],
       [30,  2,  3],
       [ 2, 48, 99],
       [30, 24, 63]])

In [32]:
x.flatten()

array([ 8, 56, 53, 50, 11, 71, 40, 56, 88, 71, 64, 15, 31, 75, 33, 67, 20,
       55, 27, 35, 31, 30, 77,  3,  2, 17,  3, 17,  2, 38, 23, 48, 43, 99,
       63, 30, 61, 74, 24, 58, 63,  4])

In [33]:
y = x.flatten()

In [34]:
y

array([ 8, 56, 53, 50, 11, 71, 40, 56, 88, 71, 64, 15, 31, 75, 33, 67, 20,
       55, 27, 35, 31, 30, 77,  3,  2, 17,  3, 17,  2, 38, 23, 48, 43, 99,
       63, 30, 61, 74, 24, 58, 63,  4])

In [35]:
np.min(y)

2

In [36]:
np.max(y)

99

In [37]:
np.mean(y)

41.333333333333336

In [39]:
np.median(y)

39.0

In [42]:
np.sort(y)

array([ 2,  2,  3,  3,  4,  8, 11, 15, 17, 17, 20, 23, 24, 27, 30, 30, 31,
       31, 33, 35, 38, 40, 43, 48, 50, 53, 55, 56, 56, 58, 61, 63, 63, 64,
       67, 71, 71, 74, 75, 77, 88, 99])

In [43]:
x

array([[ 8, 56, 53, 50, 11, 71, 40],
       [56, 88, 71, 64, 15, 31, 75],
       [33, 67, 20, 55, 27, 35, 31],
       [30, 77,  3,  2, 17,  3, 17],
       [ 2, 38, 23, 48, 43, 99, 63],
       [30, 61, 74, 24, 58, 63,  4]])

In [45]:
np.mean(x)

41.333333333333336

In [46]:
# minimum value of each column
np.min(x, axis=0)

array([ 2, 38,  3,  2, 11,  3,  4])

In [47]:
# minimum value of each row
np.min(x, axis=1)

array([ 8, 15, 20,  2,  2,  4])

In [48]:
# mean of each column
np.mean(x, axis=0)

array([26.5       , 64.5       , 40.66666667, 40.5       , 28.5       ,
       50.33333333, 38.33333333])